# Practice - Diabetes dataset
### Instructions
- This dataset is for your practice
- Can you define what type of problem this is?
- Clean & inspect your data
- Conduct Exploratory Data Analysis
- Apply Feature Scaling, extraction if necessary
- Build your model

If you get stuck at something you can always refer to class lessons and the previous case studies

In [1]:
import pandas as pd
import numpy as np

data = pd.read_csv('diabetes.csv')
data.head(10)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72.0,35,0,33.6,0.627,50.0,1
1,1,85,66.0,29,0,26.6,0.351,31.0,0
2,8,183,64.0,0,0,23.3,0.672,32.0,1
3,1,89,66.0,23,94,28.1,0.167,21.0,0
4,0,137,40.0,35,168,43.1,2.288,33.0,1
5,5,116,74.0,0,0,25.6,0.201,30.0,0
6,3,78,50.0,32,88,31,0.248,26.0,1
7,10,115,0.0,0,0,Nan,0.134,29.0,0
8,2,197,70.0,45,543,30.5,Nan,53.0,1
9,8,125,96.0,0,0,0,0.232,54.0,1